### ISSUE TITLE
ft: create ssh key on window

### ISSUE THREAD

**Issue by 9bany** [9bany/git-switch#39]

**Comment by Bi-Bi-ic** [comment]
## Researches:

- Using 3rd Tools:
  - [Git](https://git-scm.com/)
  - [OpenSSH](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse)
  - [Putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html)

- Default `.ssh` directory location: 
  - `C:\Users\[your user name]\.ssh` (%USERPROFILE%\.ssh)

- Cases for `git-switch`'s flowchart:
  - Get location's directory `.ssh` as input parameter. (user's input)
  - Set default location `.ssh` if user not give parameter.
  - Temporal directory for `git-switch`'s functions with ssh-keys.

## References
- https://support.automaticsync.com/hc/en-us/articles/202357115-Generating-an-SSH-Key-on-Windows#:~:text=The%20public%20part%20of%20the,ssh%20.
- https://stackoverflow.com/questions/10146398/ssh-keygen-is-not-recognized-as-an-internal-or-external-command
- https://stackoverflow.com/questions/31813080/generate-new-ssh-keys-in-windows-10-11
- https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement

**Comment by Bi-Bi-ic** [comment]
@9bany First Drafts for Issue
