### ISSUE TITLE
Eroor: Cant not switch user with username

### ISSUE THREAD

**Issue by 9bany** [9bany/git-switch#54]
<img width="1916" alt="Screen Shot 2022-05-10 at 17 03 46" src="https://user-images.githubusercontent.com/53461381/167604239-98dba1dd-34db-4171-83fc-3676624267c0.png">

**Comment by olivanderwood** [comment]
https://github.com/9bany/git-switch/pull/57

**Comment by 9bany** [comment]
@olivanderwood have some error like this
<img width="884" alt="Screen Shot 2022-05-11 at 07 53 51" src="https://user-images.githubusercontent.com/53461381/167747727-c17e4065-8c6a-489a-946f-3df509311864.png">
